### PR TITLE
Move Main, MainApp and UI to commons

### LINKED ISSUE #253: Abstract common components to commons package
#### Description
Common classes and interfaces used by both transaction and address are scattered within the `spleetwaise.address` package, making the codebase less modular and harder to maintain. This organization can lead to code duplication and inconsistencies as storage functionality is reused across multiple packages.

#### Expected Outcome
- [x] All storage-related classes and interfaces are moved to a centralized package (`spleetwaise.commons`).
- [x] All utils classes and interfaces are moved to a centralized package (`spleetwaise.commons`).
- [ ] All UI classes and interfaces are moved to a centralized package (`spleetwaise.commons`).
- [ ] MainApp and Main is moved under commons
- Codebase structure is improved, allowing better modularity and reusability.
- Import statements are updated across files to reflect the new structure, ensuring smooth functionality.

#### To Do
- Verify that DG accurately reflects the new organization to avoid confusion for future developers. @rollingpencil 

---

This issue aims to improve the codebase structure by centralizing storage-related classes, making it more maintainable and reusable for future development.

### PR DESCRIPTION
**Pull request by SeeYangZhi**
Closes #253 

This pull request refactors the package structure of the project by moving several classes from the `spleetwaise.address` package to the `spleetwaise.commons` package. The changes affect both main application classes and UI components.

### Changes

1. **Package Refactoring:**
   - The `Main`, `MainApp`, and various UI components such as `CommandBox`, `HelpWindow`, `MainWindow`, `PersonCard`, `PersonListPanel`, `ResultDisplay`, `StatusBarFooter`, `Ui`, `UiManager`, and `UiPart` have been moved from `spleetwaise.address` to `spleetwaise.commons`.
   - This change is reflected across multiple files, including Java source files, test files, and FXML resources.

2. **Import Adjustments:**
   - All relevant import statements have been updated to reflect the new package paths. For example, imports like `spleetwaise.address.ui.UiPart` have been changed to `spleetwaise.commons.ui.UiPart`.

3. **Documentation Update:**
   - The `SettingUp.md` documentation has been updated to reflect the new package path for running the main application class.

### To Do

- **Further Documentation:** If there are any architectural documents, they should also be updated to reflect these changes. @rollingpencil

### CODE REVIEW

**Comment by seanlim** [comment]
> ### To Do
> * **Further Documentation:** If there are any architectural documents, they should also be updated to reflect these changes. @rollingpencil

Have you created a separate issue for this?

**Comment by SeeYangZhi** [comment]
> > ### To Do
> > 
> > * **Further Documentation:** If there are any architectural documents, they should also be updated to reflect these changes. @rollingpencil
> 
> Have you created a separate issue for this?

There is an existing issue on Models https://github.com/AY2425S1-CS2103-F13-1/tp/issues/168 and he will help to oversee the entire DG as agreed upon, @rollingpencil should also look at what is missing in DG and create issues so that @seanlim can help with.

**Review by rollingpencil — APPROVED** [review]
LGTM

**Review by seanlim — CHANGES_REQUESTED** [review]
Great stuff on this PR!

One additional thing you might wanna do for completeness is to refactor `AddressBookModel.[get|set]UserPrefs` to `common...Model.[get|set]UserPrefs`.

Since `UserPrefs` is now a `common` construct, it makes more sense for the common model to own it. Address book should retrieve whatever it needs from `UserPrefs` from the common model instead.

**Pull request merged**
