### PR TITLE
feat: add clearTxn for user testing, update User Guide with clearTxn command

### LINKED ISSUE #84: Update UG for addTxn, listTxn & clearTxn
Update the user guide to include all of milestone 1.2's changes

### PR DESCRIPTION
**Pull request by SeeYangZhi**
- Added `clearTxn` to parser for testing
- Added documentation for the `clearTxn` command in the User Guide.
- Updated the Command Summary for Transactions section.

closes #84

### CODE REVIEW

**Comment by SeeYangZhi** [comment]
Try squash merge

**Review by seanlim — DISMISSED** [review]
LGTM

**Comment by SeeYangZhi** [comment]
@Dino-Nuggies Would you like to try to review this PR?

**Review by rollingpencil — APPROVED** [review]
LGTM

**Pull request merged**
