### PR TITLE
Fix storage not loaded in transaction model

### LINKED ISSUE #135: Transaction Storage Related Enhancements
# Issues
1. transactionBook.json seems to have nondeterministic behaviour when saving. 
> After deleting a person, occasionally the transactionBook.json updates immediately, occasionally it has to be triggered by `listTxn` command, and sometimes after `listTxn` command it still does not save the updated transactionBook.  

> After deleting a person, as mentioned, the transactionBook.json does not update immediately. In this case exiting the program should likely trigger an auto-save with the latest transactionbook object, but this does not happen.

> Only if there exists a transactionBook.json, then the saving occurs and be seen immediately after a `addTxn` command.

# Considerations
We might want to consider implementing the following behaviours
1. transactionBook.json should be generated upon exit for first-time users with dummy transactions, similar to how addressBook.json saves the records of the dummy person objects.

### PR DESCRIPTION
**Pull request by seanlim**
Closes #135

### CODE REVIEW

**Comment by seanlim** [comment]
Holding off on this and moving it to milestone 1.4 as referential integrity issues still persist.

## TODO:

- [ ] Fix referential integrity issues (When a person is deleted, what should happen to their transactions?)
- [ ] Figure out a robust way to implement tests for this

**Comment by GavinSin** [comment]
@seanlim is this PR still needed? I see that `StorageUtil` are removed in your other PR on `CommonModel`.

**Comment by seanlim** [comment]
> @seanlim is this PR still needed? I see that `StorageUtil` are removed in your other PR on `CommonModel`.

Yes, this PR still needs to be approved because PR #145 is based on this branch

**Review by SeeYangZhi — APPROVED** [review]
LGTM, quick fix for txn storage

**Pull request merged**
